version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - $AUDIODIR/audiobooks:/audiobooks
      - $AUDIODIR/podcasts:/podcasts
      - $CONFIGDIR/audiobookshelf:/config
      - $AUDIODIR/metadata:/metadata

