---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - CLI_ARGS= #optional
    volumes:
      - $CONFIGDIR/duplicati:/config
      - $CLONEDIR:/backups
      - /home/none:/serverHomeDir
      - $CONFIGDIR:/source
    ports:
      - $DUPLICATI_PORT:8200
    restart: unless-stopped
