services:
  file-browser:
    image: filebrowser/filebrowser:latest
    container_name: file-browser
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CLONEDIR:/srv
      - $DOWNLOADDIR:/downloaddir
      - $CONFIGDIR/filebrowser:/config/filebrowser.db
      - $CONFIGDIR/filebrowser:/config/settings.json
    ports:
      -  8083:80

    restart: unless-stopped
