services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=$TZ
       ports:
            - 5055:5055
       volumes:
            - $CONFIGDIR/jellyseerr:/app/config
       restart: unless-stopped
