---
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/readarr:/config
      - $BOOKDIR/:/data/books #optional
      - $DOWNLOADDIR/completed:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
