---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=$PUID
      - PGID=$PUID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/radarr/config:/config
      - $TVDIR:/data/tvshows
      - $MOVIEDIR:/data/movies
      - $TVDIR2:/data/tvshows2
      - $MOVIEDIR2:/data/movies2
      - $DOWNLOADDIR:/downloads #optional
    restart: unless-stopped

    #########################################################################
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/sonarr/config:/config
      - $TVDIR:/data/tvshows
      - $TVDIR2:/data/tvshows2
      - $DOWNLOADDIR:/downloads #optional
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/prowlarr/config:/config
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    ports:
      - 6789:6789
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - NZBGET_USER=$NZBGET_USER
      - NZBGET_PASS=$NZBGET_PASS
    volumes:
      - $CONFIGDIR/nzbget:/config
      - $DOWNLOADDIR:/downloads #optional
    restart: unless-stopped


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    ports:
      - 8089:8089
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8089
    volumes:
      - $CONFIGDIR/qtorrent:/config
      - $TORRENTDIR:/downloads
      - $DOWNLOADDIR:/nzbdownloads #optional
    restart: always

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    ports:
      - 9117:9117
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - $CONFIGDIR/jacket/data:/config
      - $CONFIGDIR/jacket/blackhole:/downloads
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/bazzar/config:/config
      - $TVDIR:/tv
      - $TVDIR2:/data/tvshows2
      - $MOVIEDIR:/movies
      - $MOVIEDIR2:/data/movies2
    ports:
      - 6767:6767
    restart: unless-stopped
