---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=$PUID
      - PGID=$PUID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/radarr/config:/config
      - $TVDIR:/data/tvshows
      - $MOVIEDIR:/data/movies
      - $DOWNLOADDIR:/downloads #optional
    restart: unless-stopped

    #########################################################################
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/sonarr/config:/config
      - $TVDIR:/data/tvshows
      - $DOWNLOADDIR:/downloads #optional
    restart: unless-stopped

    #########################################################################
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/prowlarr/config:/config
    restart: unless-stopped

    #########################################################################
    
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    ports:
      - 6789:6789
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - NZBGET_USER=$NZBGET_USER
      - NZBGET_PASS=$NZBGET_PASS
    volumes:
      - $CONFIGDIR/nzbget:/config
      - $DOWNLOADDIR:/downloads #optional
    restart: unless-stopped

    #########################################################################
    
  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    restart: always
    ports:
      - "9705:9705"
    volumes:
      - $CONFIGDIR/huntarr/data:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
