---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PUID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/radarr/config:/config
      - $TVDIR:/data/tvshows
      - $MOVIEDIR:/data/movies
      - $DOWNLOADDIR:/downloads #optional
    ports:
      - $RADARR_7878:7878
    restart: unless-stopped

    #########################################################################
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/sonarr/config:/config
      - $TVDIR:/data/tvshows
      - $DOWNLOADDIR:/downloads #optional
    ports:
      - $SONARR_8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/prowlarr/config:/config
    ports:
      - $PROWLARR_9696:9696
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - NZBGET_USER=$NZBGET_USER
      - NZBGET_PASS=$NZBGET_PASS
    volumes:
      - $CONFIGDIR/nzbget:/config
      - $DOWNLOADDIR:/downloads #optional
    ports:
      - $NZBGET_6789:6789
    restart: unless-stopped



