---
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=PUID
      - PGID=PGID
      - TZ=TZ
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - $CONFIGDIR/calibre:/config
      - $CLONEDIR/books:/books
    ports:
      - 8084:8083
    restart: unless-stopped

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=PUID
      - PGID=PGID
      - TZ=TZ
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - $CONFIGDIR/calibre:/config
      - $CLONEDIR/books:/books
    ports:
      - 8070:8080
      - 8181:8181
      - 8085:8081
    restart: unless-stopped

