---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/heimdall:/config
    ports:
      - $HEIMDALL_80:80
      - $HEIMDALL_443:443
    restart: unless-stopped

