services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - $CLONEDIR/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: nextcloud
    ports:
      - $POSTGRES_5432:5432
      

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - $ADMINER_8080:8080

