CRON_TIMES: 0 0 * * *
DB_TYPE: sqlite
EXCLUDE_DOWNLOADED: true
EXCLUDE_REQUESTED: true
FILTER_GENRES_EXCLUDE: []
FILTER_INCLUDE_NO_RATING: true
FILTER_LANGUAGE:
- english_name: English
  id: en
- english_name: Korean
  id: ko
FILTER_STREAMING_SERVICES: []
HONOR_JELLYSEER_DISCOVERY: false
JELLYFIN_API_URL: http://10.10.10.106:30013
JELLYFIN_LIBRARIES:
- id: a656b907eb3a73532e40e44b968d0225
  name: Shows
- id: f137a2dd21bbc1b99aa5c0f6bf02a805
  name: Movies
JELLYFIN_TOKEN: 3ce0ae7316484c5dbbfc58b16f7d2a72
MAX_CONTENT_CHECKS: '10'
MAX_SIMILAR_MOVIE: '5'
MAX_SIMILAR_TV: '2'
PLEX_LIBRARIES: []
SEARCH_SIZE: '20'
SEER_API_URL: http://10.10.50.11:5055
SEER_TOKEN: MTc0MjY3NTY0Njc0NWZkMjAzMGE3LWY5MTUtNDQzYy05YjVlLTM1MzZlNjUxYjM2YQ==
SEER_USER_NAME: odins@nygard.io
SEER_USER_PSW: 1a2b3c45
SELECTED_SERVICE: jellyfin
SELECTED_USERS:
- id: 7967395b54784a9fb170284b97a33359
  name: odin
TMDB_API_KEY: a22e05131a3a264b756c11dc4280c4a3
